name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run rubocop
        env:
          RAILS_ENV: test
        run: |
          bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.11
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install libffi6
        run: |
          wget http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          sudo apt install ./libffi6_3.2.1-8_amd64.deb
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Configure database
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          ENCRYPTION_SERVICE_SALT: ${{ secrets.ENCRYPTION_SERVICE_SALT_FOR_RSPEC }}
        run: |
          bundle exec rake db:create db:schema:load
      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: coverage-report
          path: coverage
  deploy-production:
    needs: [rubocop, rspec]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build and push production
        env:
          K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
          K8S_CLUSTER_CERT: ${{ secrets.K8S_CLUSTER_CERT }}
          K8S_CLUSTER_NAME: ${{ secrets.K8S_CLUSTER_NAME }}
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          ECR_USERNAME: ${{ secrets.ECR_USERNAME }}
          ECR_CREDENTIALS_SECRET: ${{ secrets.ECR_CREDENTIALS_SECRET }}
        run: ./scripts/environment_setup.sh build_and_push.sh
