name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build and push production
        env:
          ENVIRONMENT: prod
          K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
          K8S_CLUSTER_CERT: ${{ secrets.K8S_CLUSTER_CERT }}
          K8S_CLUSTER_NAME: ${{ secrets.K8S_CLUSTER_NAME }}
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          ECR_USERNAME: ${{ secrets.ECR_USERNAME }}
          ECR_CREDENTIALS_SECRET: ${{ secrets.ECR_CREDENTIALS_SECRET }}
        run: ./scripts/build_and_push.sh
